import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const roboto = Roboto({ subsets: ["latin"], weight: ["400","500", "700"] });

export const metadata: Metadata = {
  title: "Medusa Eventos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${roboto.className}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
